name = "cfwebdav"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[vars]
USERNAME = "$USERNAME"
PASSWORD = "$PASSWORD"
BUCKET_NAME = "mark-editor"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "mark-editor"